services:
  orders-ms-db:
    container_name: orders-ms-db
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data # Persist data
    ports:
      - '5432:5432' # localport:containerport
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 30s
      timeout: 10s
      retries: 5
